<template>
  <MobileShell :screen="screen">
    <template v-if="screen==='profile'">
      <view class="card profile"><view class="avatar"><Icon name="users" :size="42" /></view><text class="card-title big">{{user?.nickname||'访客'}}</text><text class="muted">{{user?`${user.account} · ${displayText(user.roleCode)}`:'访客'}}</text><view v-if="!user" class="guest-note">访客仅可浏览公开的可领养动物与已发布公告；收藏、申请、发布线索等操作需先登录。</view></view>
      <view class="card menu"><button v-if="user" class="btn wide" @click="goto('profileEdit')">编辑资料</button><button v-if="role==='RESCUER'" class="btn wide" @click="goto('responsibleAnimals')">我负责的动物</button><button v-if="role==='RESCUER'" class="btn wide" @click="goto('rescuerFollowups')">负责动物回访</button><button v-if="user" class="btn wide" @click="goto('records')">我的申请 / 领养记录</button><button v-if="user" class="btn wide" @click="goto('favorites')">我的收藏</button><button class="btn wide" @click="goto('announcements')">公告</button><button v-if="!user" class="btn wide" @click="goto('login')">登录页面</button><button v-if="!user" class="btn wide" @click="goto('register')">注册页面</button><button v-if="user" class="btn danger wide" @click="logout">退出登录</button></view>
    </template>

    <template v-else-if="screen==='profileEdit'">
      <BackButton/><view class="title">编辑个人资料</view><view class="card"><FormField label="昵称" :error="profileErrors.nickname"><input v-model="profileForm.nickname" class="input" maxlength="50"/></FormField><FormField label="手机号" :error="profileErrors.phone"><input v-model="profileForm.phone" class="input" maxlength="20" placeholder="可空"/></FormField><view class="notice">需要调整救助资格？请联系平台管理员。</view><button class="btn primary wide" :disabled="submitState.submitting.value" @click="saveProfile">{{submitState.submitting.value?'保存中…':'保存资料'}}</button></view>
    </template>

    <template v-else-if="screen==='login'">
      <BackButton/><view class="title">登录</view><view class="card"><FormField label="账号" :error="loginErrors.account"><input v-model="loginForm.account" class="input" maxlength="50" placeholder="账号"/></FormField><FormField label="密码" :error="loginErrors.password"><input v-model="loginForm.password" class="input" password placeholder="8～64字符"/></FormField><text v-if="actionError" class="inline-error">{{actionError}}</text><button class="btn primary wide" :disabled="submitState.submitting.value" @click="login">{{submitState.submitting.value?'登录中…':'登录'}}</button><button class="btn wide" @click="goto('register')">没有账号？注册</button></view>
    </template>

    <template v-else-if="screen==='register'">
      <BackButton/><view class="title">注册</view><view class="card"><FormField label="账号" :error="registerErrors.account"><input v-model="registerForm.account" class="input" maxlength="50" placeholder="4～50 位字母、数字或下划线"/></FormField><FormField label="密码" :error="registerErrors.password"><input v-model="registerForm.password" class="input" :password="!showPassword" placeholder="密码 8～64 字符"/></FormField><FormField label="昵称" :error="registerErrors.nickname"><input v-model="registerForm.nickname" class="input" maxlength="50" placeholder="可空"/></FormField><FormField label="手机号" :error="registerErrors.phone"><input v-model="registerForm.phone" class="input" maxlength="20" placeholder="可选"/></FormField><FormField label="确认密码" :error="registerErrors.confirm"><input v-model="registerForm.confirm" class="input" :password="!showPassword" placeholder="请再次输入密码"/></FormField><button class="btn wide" @click="showPassword=!showPassword">{{showPassword?'隐藏密码':'显示密码'}}</button><view class="notice">注册即可参与领养与线索发布，救助资格由管理员审核。</view><text v-if="actionError" class="inline-error">{{actionError}}</text><button class="btn primary wide" :disabled="submitState.submitting.value" @click="register">{{submitState.submitting.value?'创建中…':'创建账号'}}</button></view>
    </template>
  </MobileShell>
</template>
<script setup>
import {reactive,computed,ref,onMounted} from 'vue'
import MobileShell from '../../components/MobileShell.vue';import BackButton from '../../components/BackButton.vue';import FormField from '../../components/FormField.vue';import Icon from '../../components/Icon.vue'
import {authApi} from '../../api/index.js';import {useAuth} from '../../store/auth.js';import {useNavigation,routes} from '../../composables/navigation.js';import {useSubmit} from '../../composables/asyncState.js';import {textRule,phoneRule,accountRule,passwordRule} from '../../composables/validation.js'
import {displayText} from '../../utils/displayText.js'
const showPassword=ref(false)
const props=defineProps({screen:{type:String,required:true}});const screen=props.screen;const auth=useAuth();const user=computed(()=>auth.state.user),role=computed(()=>user.value?.roleCode);const {goto,switchMain}=useNavigation();const submitState=useSubmit(),actionError=ref('');const profileForm=reactive({nickname:'',phone:''}),profileErrors=reactive({nickname:'',phone:''});const loginForm=reactive({account:'',password:''}),loginErrors=reactive({account:'',password:''});const registerForm=reactive({account:'',password:'',confirm:'',nickname:'',phone:''}),registerErrors=reactive({account:'',password:'',confirm:'',nickname:'',phone:''})
function validateLogin(){loginErrors.account=accountRule(loginForm.account);loginErrors.password=passwordRule(loginForm.password);return !Object.values(loginErrors).some(Boolean)}function validateRegister(){registerErrors.confirm=registerForm.password===registerForm.confirm?'':'两次密码输入不一致';registerErrors.account=accountRule(registerForm.account);registerErrors.password=passwordRule(registerForm.password);registerErrors.nickname=textRule(registerForm.nickname,{label:'昵称',required:false,max:50});registerErrors.phone=phoneRule(registerForm.phone);return !Object.values(registerErrors).some(Boolean)}function validateProfile(){profileErrors.nickname=textRule(profileForm.nickname,{label:'昵称',max:50});profileErrors.phone=phoneRule(profileForm.phone);return !Object.values(profileErrors).some(Boolean)}
async function login(){if(!validateLogin())return;actionError.value='';await submitState.submit(async()=>{try{const r=await authApi.login({account:loginForm.account.trim(),password:loginForm.password});if(r.user?.roleCode==='ADMIN'){actionError.value='管理员请使用电脑管理端';return}auth.setSession(r.accessToken,r.user);const target=uni.getStorageSync('petlink_mobile_return_to');uni.removeStorageSync('petlink_mobile_return_to');if(target&&routes[target.name])goto(target.name,target.q||{});else switchMain('home')}catch(e){actionError.value=e?.userMessage||'登录失败，请稍后重试'}})}
async function register(){if(!validateRegister())return;actionError.value='';await submitState.submit(async()=>{try{await authApi.register({account:registerForm.account.trim(),password:registerForm.password,nickname:registerForm.nickname.trim()||undefined,phone:registerForm.phone.trim()||null});uni.showToast({title:'注册成功'});uni.redirectTo({url:'/pages/login/index?account='+encodeURIComponent(registerForm.account.trim())})}catch(e){actionError.value=e?.userMessage||'注册失败，请稍后重试'}})}
async function saveProfile(){if(!validateProfile())return;await submitState.submit(async()=>{const r=await authApi.patchMe({nickname:profileForm.nickname.trim(),phone:profileForm.phone.trim()||null});auth.setUser(r);uni.showToast({title:'已保存'})})}function logout(){auth.logout();switchMain('home')}
onMounted(()=>{if(screen==='login'){const pages=getCurrentPages();const current=pages[pages.length-1];loginForm.account=current?.options?.account||''}if(screen==='profileEdit')Object.assign(profileForm,{nickname:user.value?.nickname||'',phone:user.value?.phone||''})})
</script>
