const bestFriendsCredit = subject => `Best Friends Animal Society · 原照片动物：${subject}`

export const animalProfiles = [
  { id:'PL-101', name:'奶糖', species:'猫', sex:'母', age:'约 3 岁', color:'黑白短毛', health:'来源档案显示已绝育、接种疫苗并植入芯片。', personality:'刚进入陌生环境时需要一点适应时间，熟悉后喜欢陪伴、抚摸和互动游戏，也会主动依偎。', requirements:'室内科学喂养；安装纱窗；允许循序适应；每天安排稳定互动时间。', image:'/assets/content/animal-naitang-cover.jpg', images:['/assets/content/animal-naitang-full.jpg','/assets/content/animal-naitang-life.jpg'], credit:bestFriendsCredit('Paradise'), sourceUrl:'https://bestfriends.org/new-york-city/adopt/213183902/paradise' },
  { id:'PL-102', name:'煤球', species:'猫', sex:'母', age:'约 11 岁', color:'玳瑁短毛', health:'来源档案显示已绝育、接种疫苗并植入芯片；高龄动物应结合最新检查制定照护计划。', personality:'亲人、爱交流，适应后喜欢梳毛、探索环境和下巴挠痒，是生活节奏稳定的陪伴型猫咪。', requirements:'适合安静稳定的室内家庭；接受高龄动物定期体检；给予充足的适应时间。', image:'/assets/content/animal-meiqiu-cover.jpg', images:['/assets/content/animal-meiqiu-full.jpg','/assets/content/animal-meiqiu-life.jpg'], credit:bestFriendsCredit('Cashmere'), sourceUrl:'https://bestfriends.org/new-york-city/adopt/214271912/cashmere' },
  { id:'PL-103', name:'豆包', species:'狗', sex:'公', age:'约 12 岁', color:'黑色短毛 / 大型', health:'来源档案显示已开放领养；具体检查、疫苗与用药记录以来源机构交接资料为准。', personality:'性格温和、喜欢人与零食，也能接受合适的犬类伙伴；虽然年长，仍然愿意参与轻松活动。', requirements:'提供防滑、舒适的休息环境；控制运动强度；愿意进行高龄犬常规检查与长期照护。', image:'/assets/content/animal-doubao-cover.jpg', images:['/assets/content/animal-doubao-full.jpg','/assets/content/animal-doubao-life.jpg'], credit:bestFriendsCredit('Zuzu'), sourceUrl:'https://bestfriends.org/sanctuary/adopt/213258367/zuzu' },
  { id:'PL-104', name:'栗子', species:'猫', sex:'母', age:'约 5 岁', color:'灰、米与白色淡三花短毛', health:'来源档案显示已开放领养；具体健康状态以最新检查与机构交接记录为准。', personality:'独立而有边界感，喜欢温和抚摸和安静休息；适合愿意观察并尊重猫咪节奏的家庭。', requirements:'室内喂养并做好门窗防护；不强行抱持；为它准备可独处、可躲藏的安全空间。', image:'/assets/content/animal-lizi-cover.jpg', images:['/assets/content/animal-lizi-full.jpg','/assets/content/animal-lizi-life.jpg'], credit:bestFriendsCredit('Sally'), sourceUrl:'https://bestfriends.org/sanctuary/adopt/56683310/sally' },
  { id:'PL-105', name:'米粒', species:'猫', sex:'公', age:'约 4 个月', color:'棕色虎斑加白短毛', health:'幼猫仍处于成长阶段；疫苗、驱虫和绝育安排应按照兽医与领养机构的实际记录继续完成。', personality:'好奇、活跃，喜欢探索和玩耍；需要通过玩具、攀爬空间和稳定互动消耗幼猫精力。', requirements:'阳台和窗户必须封网；完成后续免疫与绝育；每天安排互动、玩耍和安全探索时间。', image:'/assets/content/animal-mili-cover.jpg', images:['/assets/content/animal-mili-full.jpg','/assets/content/animal-mili-life.jpg'], credit:bestFriendsCredit('Moss'), sourceUrl:'https://bestfriends.org/sanctuary/adopt/214077523/moss' },
  { id:'PL-106', name:'阿布', species:'狗', sex:'公', age:'约 3 岁 6 个月', color:'浅棕短毛 / 中型', health:'来源档案显示已开放领养；具体健康状态及运动限制以最新检查和交接记录为准。', personality:'活泼、亲人，喜欢其他狗狗，运动意愿强，也很享受和照护者一起互动。', requirements:'每天保证户外活动和正向训练；出门全程牵引；适合愿意持续提供运动与陪伴的家庭。', image:'/assets/content/animal-abu-cover.jpg', images:['/assets/content/animal-abu-full.jpg','/assets/content/animal-abu-life.jpg'], credit:bestFriendsCredit('Bubs'), sourceUrl:'https://bestfriends.org/sanctuary/adopt/213764787/bubs' }
]

export const rescueStories = [
  { slug:'xiaoman', name:'小满', sourceName:'Marble', profile:'猫 · 康复档案', area:'来源机构公开记录', status:'恢复照护中', summary:'这只幼猫被转入救助机构时两条后腿严重骨折。专科医生为左腿实施截肢，并用金属针和夹板稳定右腿；随后通过换药、激光治疗、营养支持和日常梳理逐步恢复。', cover:'/assets/content/rescue-xiaoman-process.jpg', images:[{src:'/assets/content/rescue-xiaoman-process.jpg',label:'治疗与换药阶段'},{src:'/assets/content/rescue-xiaoman-recovery.jpg',label:'恢复期日常照护'}], fallback:'/assets/pudding-cat-card-v2.webp', credit:bestFriendsCredit('Marble'), sourceUrl:'https://bestfriends.org/stories/features/faces-no-kill-cat-heals-injury-style', note:'图片与病例信息可通过来源链接查看。', milestones:[{time:'接诊期',title:'评估复杂骨折',text:'完成止痛、补液、影像检查，并转诊专科评估。'},{time:'手术期',title:'稳定受伤肢体',text:'左后腿截肢，右腿使用金属针和夹板固定。'},{time:'恢复期',title:'持续换药与康复',text:'通过换药、激光治疗、营养和互动照护逐步恢复活力。'}] },
  { slug:'afu', name:'阿福', sourceName:'David Bowie', profile:'狗 · 康复档案', area:'来源机构公开记录', status:'长期健康管理', summary:'Bowie 刚到救助机构时皮肤发炎、毛发稀疏，身体虚弱且几乎不愿活动。常规螨虫治疗无效后，兽医确认是罕见的自身免疫性皮肤病，并通过针对性用药、规律洗护和寄养照护帮助它重新恢复活力。', cover:'/assets/content/rescue-afu-process.jpg', images:[{src:'/assets/content/rescue-afu-process.jpg',label:'治疗与洗护阶段'},{src:'/assets/content/rescue-afu-recovery.jpg',label:'恢复后户外活动'}], fallback:'/assets/ahei-black-dog-card-v2.webp', credit:bestFriendsCredit('David Bowie'), sourceUrl:'https://bestfriends.org/stories/features/faces-no-kill-dog-goes-shutdown-smiling', note:'图片与病例信息可通过来源链接查看。该病需要持续用药和定期复查。', milestones:[{time:'初诊期',title:'排查皮肤病因',text:'常规治疗效果不佳后，继续检查并确认自身免疫性疾病。'},{time:'治疗期',title:'用药与规律洗护',text:'在寄养家庭中接受针对性药物、舒缓洗护和营养照护。'},{time:'稳定期',title:'恢复活动与社交',text:'体重和毛发逐步恢复，开始玩耍并与其他狗狗互动。'}] },
  { slug:'huidou', name:'灰豆', sourceName:'Coop', profile:'兔 · 康复档案', area:'来源机构公开记录', status:'已恢复活动', summary:'Coop 被发现时后肢瘫痪、营养不良，无法正常清洁自己。兽医给予抗生素、止痛药、皮下补液并排除寄生虫感染，照护团队随后用物理治疗和安全草地活动帮助它重新站立和跳跃。', cover:'/assets/content/rescue-huidou-process.jpg', images:[{src:'/assets/content/rescue-huidou-process.jpg',label:'兽医检查阶段'},{src:'/assets/content/rescue-huidou-recovery.jpg',label:'恢复后草地活动'}], fallback:'/assets/coffee-kitten-card-v2.webp', credit:bestFriendsCredit('Coop'), sourceUrl:'https://bestfriends.org/stories/features/partially-paralyzed-rabbit-gets-hopping-again', note:'图片与病例信息可通过来源链接查看。案例说明了兔类救助对医疗、环境和持续康复记录的共同需求。', milestones:[{time:'接诊期',title:'稳定身体状况',text:'完成清洁、营养支持、止痛、抗生素和皮下补液。'},{time:'观察期',title:'首次重新站立',text:'约一周后开始抬起后躯，并逐渐迈出不稳定的步伐。'},{time:'康复期',title:'物理治疗与草地练习',text:'通过腿部活动训练和安全草地练习逐步恢复跳跃。'}] }
]

export const familyLetters = [
  { name:'Chip 的新家近况', period:'领养后约 5 年', quote:'从最初躲藏，到主动依偎家人并融入有猫有狗的家庭，它终于拥有稳定而长久的陪伴。', detail:'来源文章记录了 Chet（到家后改名 Chip）逐步适应家庭、与其他动物建立关系的过程。', image:'/assets/content/family-xiaoman-02.jpg', fallback:'/assets/pudding-cat-card-v2.webp', credit:bestFriendsCredit('Chet / Chip'), sourceUrl:'https://bestfriends.org/stories/features/adoption-update-worlds-cuddliest-cat' },
  { name:'Nina 的新家近况', period:'训练与领养回访', quote:'从害怕陌生人、难以牵引，到能参加外出活动并被家庭接纳，耐心和训练让它逐渐建立信任。', detail:'来源文章用连续照片记录了 Nina 在收容、训练、社交、被领养和新家生活中的变化。', image:'/assets/content/family-doubao-02.jpg', fallback:'/assets/ahei-black-dog-card-v2.webp', credit:bestFriendsCredit('Nina'), sourceUrl:'https://bestfriends.org/stories/features/shelter-dogs-journey-home-photos' },
  { name:'Bruce 的四年后', period:'领养后 4 年+', quote:'幼猫和家中的孩子一起长大，从最初的玩耍伙伴变成彼此日常生活里稳定的陪伴。', detail:'来源文章记录 Bruce 从约三个月大被领养，到四年后仍与家庭共同成长的长期回访。', image:'/assets/content/family-mili-02.jpg', fallback:'/assets/coffee-kitten-card-v2.webp', credit:bestFriendsCredit('Bruce'), sourceUrl:'https://bestfriends.org/stories/videos/adoption-update-baby-and-kitten-grow-together' }
]

export const serviceScenes = [
  { title:'日常照护与物资协作', text:'志愿者分工完成喂养、清洁、转运准备和现场记录。', image:'/assets/content/service-volunteers.jpg', credit:'用户提供' },
  { title:'健康检查与持续建档', text:'检查结果、治疗进展和后续注意事项持续进入动物健康档案。', image:'/assets/content/service-medical.jpg', credit:'Tima Miroshnichenko / Pexels' }
]

export const trustPractices = [
  { number:'01', title:'过程有迹可循', text:'线索审核、任务接取和每次救助记录都有时间与责任人。' },
  { number:'02', title:'健康情况不美化', text:'已知病史、治疗进展和后续照护要求如实进入动物档案。' },
  { number:'03', title:'领养不是先到先得', text:'结合居住条件、家庭共识、照护经验和动物需求综合审核。' },
  { number:'04', title:'回访尊重隐私', text:'公开故事只使用经许可、去身份化的内容，完整资料仅授权角色可见。' }
]
