import {idempotencyHeaders} from '../composables/idempotency.js';import {request,uploadTemporary,mediaUrl} from './request.js';const p=x=>encodeURIComponent(String(x))
export const authApi={register:d=>request('/auth/register',{method:'POST',data:d}),login:d=>request('/auth/login',{method:'POST',data:d}),me:()=>request('/users/me'),patchMe:d=>request('/users/me',{method:'PATCH',data:d}),uploadTemporary}
export const clueApi={key:()=>request('/rescue-clues/idempotency-keys',{method:'POST'}),create:(d,k)=>request('/rescue-clues',{method:'POST',data:d,headers:idempotencyHeaders(k)}),mine:q=>request('/rescue-clues/me'+qs(q)),detail:id=>request(`/rescue-clues/${p(id)}`),patch:(id,d)=>request(`/rescue-clues/${p(id)}`,{method:'PATCH',data:d}),addImages:(id,d)=>request(`/rescue-clues/${p(id)}/images`,{method:'POST',data:d}),deleteImage:(id,i)=>request(`/rescue-clues/${p(id)}/images/${p(i)}`,{method:'DELETE'}),withdraw:id=>request(`/rescue-clues/${p(id)}/withdraw`,{method:'POST'}),adminList:q=>request('/admin/rescue-clues'+qs(q)),audit:(id,d)=>request(`/admin/rescue-clues/${p(id)}/audit`,{method:'POST',data:d}),waiting:q=>request('/rescue-clues/waiting-acceptance'+qs(q)),media:i=>mediaUrl(`/media/rescue-clue-images/${p(i)}`)}
export const rescueApi={accept:id=>request(`/rescue-clues/${p(id)}/accept`,{method:'POST'}),mine:q=>request('/rescue-tasks/me'+qs(q)),detail:id=>request(`/rescue-tasks/${p(id)}`),start:id=>request(`/rescue-tasks/${p(id)}/start`,{method:'POST'}),addRecord:(id,d)=>request(`/rescue-tasks/${p(id)}/records`,{method:'POST',data:d}),records:id=>request(`/rescue-tasks/${p(id)}/records`),result:(id,d)=>request(`/rescue-tasks/${p(id)}/result`,{method:'POST',data:d}),cancel:(id,d)=>request(`/admin/rescue-tasks/${p(id)}/cancel`,{method:'POST',data:d}),resolve:(id,d)=>request(`/admin/rescue-tasks/${p(id)}/failure-resolution`,{method:'POST',data:d})}
export const animalApi={list:q=>request('/animals'+qs(q)),detail:id=>request(`/animals/${p(id)}`),responsible:q=>request('/animals/responsible/me'+qs(q)),patch:(id,d)=>request(`/animals/${p(id)}`,{method:'PATCH',data:d}),addImages:(id,d)=>request(`/animals/${p(id)}/images`,{method:'POST',data:d}),deleteImage:(id,i)=>request(`/animals/${p(id)}/images/${p(i)}`,{method:'DELETE'}),addHealth:(id,d)=>request(`/animals/${p(id)}/health-records`,{method:'POST',data:d}),health:id=>request(`/animals/${p(id)}/health-records`),status:(id,d)=>request(`/animals/${p(id)}/status-actions`,{method:'POST',data:d}),media:i=>mediaUrl(`/media/animal-images/${p(i)}`)}
export const adoptionApi={apply:(id,d)=>request(`/animals/${p(id)}/adoption-applications`,{method:'POST',data:d}),mine:q=>request('/adoption-applications/me'+qs(q)),application:id=>request(`/adoption-applications/${p(id)}`),withdraw:id=>request(`/adoption-applications/${p(id)}/withdraw`,{method:'POST'}),adminList:q=>request('/admin/adoption-applications'+qs(q)),audit:(id,d)=>request(`/admin/adoption-applications/${p(id)}/audit`,{method:'POST',data:d}),records:q=>request('/adoption-records/me'+qs(q)),record:id=>request(`/adoption-records/${p(id)}`),overview:id=>request(`/animals/${p(id)}/adoption-overview`)}
export const followupApi={create:(id,d)=>request(`/adoption-records/${p(id)}/follow-ups`,{method:'POST',data:d}),list:id=>request(`/adoption-records/${p(id)}/follow-ups`),detail:id=>request(`/follow-ups/${p(id)}`),admin:q=>request('/admin/follow-ups'+qs(q)),rescuer:q=>request('/rescuer/follow-ups'+qs(q)),media:i=>mediaUrl(`/media/follow-up-images/${p(i)}`)}
export const contentApi={favorite:id=>request(`/animals/${p(id)}/favorite`,{method:'POST'}),unfavorite:id=>request(`/animals/${p(id)}/favorite`,{method:'DELETE'}),favorites:q=>request('/favorites/me'+qs(q)),announcements:q=>request('/announcements'+qs(q)),announcement:id=>request(`/announcements/${p(id)}`),createAnnouncement:d=>request('/admin/announcements',{method:'POST',data:d}),adminAnnouncements:q=>request('/admin/announcements'+qs(q)),adminAnnouncement:id=>request(`/admin/announcements/${p(id)}`),patchAnnouncement:(id,d)=>request(`/admin/announcements/${p(id)}`,{method:'PATCH',data:d}),publish:(id,version)=>request(`/admin/announcements/${p(id)}/publish`,{method:'POST',data:{version}}),withdrawAnnouncement:(id,version)=>request(`/admin/announcements/${p(id)}/withdraw`,{method:'POST',data:{version}})}
export const adminApi={users:q=>request('/admin/users'+qs(q)),user:id=>request(`/admin/users/${p(id)}`),enable:id=>request(`/admin/users/${p(id)}/enable`,{method:'POST'}),disable:id=>request(`/admin/users/${p(id)}/disable`,{method:'POST'}),promote:id=>request(`/admin/users/${p(id)}/promote-rescuer`,{method:'POST'}),tasks:q=>request('/admin/rescue-tasks'+qs(q)),animals:q=>request('/admin/animals'+qs(q)),records:q=>request('/admin/adoption-records'+qs(q)),stats:()=>request('/admin/stats/overview'),trends:q=>request('/admin/stats/trends'+qs(q))}
function qs(o={}){const arr=Object.entries(o).filter(([,v])=>v!==''&&v!==undefined&&v!==null).map(([k,v])=>`${encodeURIComponent(k)}=${encodeURIComponent(v)}`);return arr.length?'?'+arr.join('&'):''}
