<template>
  <PageHeader title="领养审核" subtitle="管理员独立审核；批准后创建领养记录并将动物置为已领养"><el-button :loading="pager.loading.value" @click="load">刷新</el-button></PageHeader>
  <div class="toolbar"><el-select v-model="status" style="width:180px" @change="search"><el-option v-for="s in statuses" :key="s" :label="displayText(s)" :value="s"/></el-select><el-input v-model="animalId" class="search-field" clearable placeholder="动物编号" aria-label="按动物编号筛选领养申请" @keyup.enter="search"/><el-input v-model="userId" class="search-field" clearable placeholder="申请人编号" aria-label="按申请人编号筛选" @keyup.enter="search"/><el-button type="primary" @click="search">查询</el-button><el-button @click="resetFilters">重置</el-button></div>
  <ListError :message="pager.error.value" @retry="load"/>
  <div class="card table-card"><el-table :data="pager.rows.value" v-loading="pager.loading.value" row-key="id" empty-text="暂无领养申请"><el-table-column prop="id" label="申请" width="100"/><el-table-column prop="animalId" label="动物" width="110"/><el-table-column prop="userId" label="申请人" width="110"/><el-table-column label="状态" width="140"><template #default="{row}"><StatusBadge :value="row.status"/></template></el-table-column><el-table-column prop="createdAt" label="提交时间" min-width="190"/><el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><el-button size="small" @click="open(row)">详情</el-button><el-button v-if="row.status==='PENDING'" size="small" type="primary" @click="open(row,true)">审核</el-button></template></el-table-column></el-table></div>
  <el-pagination class="pager" background layout="sizes,prev,pager,next,total" :page-sizes="[10,20,50]" :total="pager.total.value" v-model:page-size="pager.size.value" v-model:current-page="pager.page.value" @size-change="changePageSize" @current-change="load"/>
  <el-dialog align-center destroy-on-close :close-on-click-modal="false" v-model="drawer" width="760px" title="领养申请详情"><div v-loading="detailLoading" class="detail-loading"><template v-if="detail"><div class="archive-row"><AuthImage class="archive-img" :src="detail.animal?.coverImageUrl" fallback="/assets/pudding-cat-hero.png"/><div><b>申请 #{{detail.id}}</b><div>{{detail.animal?.name||('动物 #'+detail.animalId)}}</div><StatusBadge :value="detail.status"/></div></div><el-descriptions :column="1" border style="margin-top:16px"><el-descriptions-item label="领养理由">{{detail.adoptionReason}}</el-descriptions-item><el-descriptions-item label="住房条件">{{detail.housingCondition}}</el-descriptions-item><el-descriptions-item label="家庭成员">{{detail.familyMembers}}</el-descriptions-item><el-descriptions-item label="养宠经验">{{detail.petExperience}}</el-descriptions-item><el-descriptions-item label="联系方式">{{detail.contact}}</el-descriptions-item><el-descriptions-item v-if="detail.rejectReason" label="拒绝原因">{{detail.rejectReason}}</el-descriptions-item></el-descriptions><div v-if="auditMode&&detail.status==='PENDING'" class="card" style="margin-top:16px"><el-radio-group v-model="decision"><el-radio-button value="APPROVE">批准</el-radio-button><el-radio-button value="REJECT">拒绝</el-radio-button></el-radio-group><el-input v-if="decision==='REJECT'" v-model="rejectReason" type="textarea" maxlength="500" show-word-limit placeholder="拒绝原因必填" style="margin-top:10px"/><el-button type="primary" :loading="saving" style="margin-top:10px" @click="audit">确认审核</el-button></div></template></div></el-dialog>
</template>
<script setup>
import {useRoute} from 'vue-router'
const route=useRoute()
import {ref,onMounted} from 'vue';import {ElMessage} from '../plugins/message.js';import PageHeader from '../components/PageHeader.vue';import StatusBadge from '../components/StatusBadge.vue';import AuthImage from '../components/AuthImage.vue';import ListError from '../components/ListError.vue';import {adoptionApi} from '../api/index.js';import {usePagination} from '../composables/usePagination.js';import {displayText} from '../utils/displayText.js'
const statuses=['PENDING','APPROVED','REJECTED','WITHDRAWN','INVALIDATED'];const status=ref(statuses.includes(String(route.query.status))?String(route.query.status):'PENDING'),animalId=ref(''),userId=ref(''),pager=usePagination({pageSize:20}),drawer=ref(false),detail=ref(null),detailLoading=ref(false),auditMode=ref(false),decision=ref('APPROVE'),rejectReason=ref(''),saving=ref(false)
async function load(){await pager.load(({page,size})=>adoptionApi.adminList({page,size,status:status.value,animalId:animalId.value||undefined,userId:userId.value||undefined})).catch(()=>{})}
function search(){if([animalId.value,userId.value].some(v=>v&&!/^[1-9]\d*$/.test(v))){ElMessage.warning('请输入有效的正整数编号');return}pager.reset();load()}
function resetFilters(){status.value='PENDING';animalId.value='';userId.value='';search()}function changePageSize(){pager.reset();load()}
async function open(row,mode=false){detail.value=null;drawer.value=true;detailLoading.value=true;auditMode.value=mode;decision.value='APPROVE';rejectReason.value='';try{detail.value=await adoptionApi.application(row.id)}catch{drawer.value=false}finally{detailLoading.value=false}}
async function audit(){if(decision.value==='REJECT'&&!rejectReason.value.trim()){ElMessage.warning('拒绝原因必填');return}if(rejectReason.value.trim().length>500){ElMessage.warning('拒绝原因不能超过 500 字');return}saving.value=true;try{await adoptionApi.audit(detail.value.id,decision.value==='APPROVE'?{decision:'APPROVE'}:{decision:'REJECT',rejectReason:rejectReason.value.trim()});drawer.value=false;ElMessage.success('审核完成');await load()}finally{saving.value=false}}
onMounted(load)
</script>
