<template>
  <PageHeader title="公告管理" subtitle="草稿 → 已发布 → 已撤回"><el-button type="primary" @click="createOpen">新建草稿</el-button><el-button :loading="pager.loading.value" @click="load">刷新</el-button></PageHeader>
  <div class="toolbar"><el-input v-model="keyword" clearable class="search-field" placeholder="搜索公告标题或正文" aria-label="搜索公告" @keyup.enter="changeFilter" @clear="changeFilter"/><el-select v-model="status" clearable placeholder="全部状态" style="width:190px" @change="changeFilter"><el-option v-for="s in ['DRAFT','PUBLISHED','WITHDRAWN']" :key="s" :value="s" :label="displayText(s)"/></el-select><el-button type="primary" @click="changeFilter">查询</el-button><el-button @click="keyword='';status='';changeFilter()">重置</el-button></div>
  <ListError :message="pager.error.value" @retry="load"/>
  <div class="card table-card"><el-table :data="pager.rows.value" v-loading="pager.loading.value" empty-text="暂无公告"><el-table-column prop="id" label="编号" width="100"/><el-table-column prop="title" label="标题"/><el-table-column label="状态" width="150"><template #default="{row}"><StatusBadge :value="row.status"/></template></el-table-column><el-table-column label="操作" width="340" fixed="right"><template #default="{row}"><el-button size="small" @click="editOpen(row)">详情/编辑</el-button><el-button v-if="row.status==='DRAFT'" size="small" type="primary" @click="publish(row)">发布</el-button><el-button v-if="row.status==='PUBLISHED'" size="small" type="warning" @click="withdraw(row)">撤回</el-button><el-button size="small" type="danger" plain :loading="deleting===row.id" @click="remove(row)">删除</el-button></template></el-table-column></el-table></div>
  <el-pagination class="pager" background layout="sizes,prev,pager,next,total" :page-sizes="[10,20,50]" :total="pager.total.value" v-model:page-size="pager.size.value" v-model:current-page="pager.page.value" @size-change="changePageSize" @current-change="load"/>
  <el-dialog v-model="dialog" :title="form.id?'公告详情':'新建公告草稿'" width="650px"><el-form label-position="top"><el-form-item label="标题" :error="formErrors.title"><el-input v-model="form.title" maxlength="200" show-word-limit/></el-form-item><el-form-item label="正文" :error="formErrors.content"><el-input v-model="form.content" type="textarea" :rows="8"/></el-form-item><div v-if="form.id" class="muted">状态 {{displayText(form.status)}}</div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="form.status==='WITHDRAWN'" @click="save">{{form.id?'保存':'创建草稿'}}</el-button></template></el-dialog>
</template>
<script setup>
import{ref,reactive,onMounted}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import PageHeader from'../components/PageHeader.vue';import StatusBadge from'../components/StatusBadge.vue';import ListError from '../components/ListError.vue';import{contentApi}from'../api/index.js';import {usePagination} from '../composables/usePagination.js';import {displayText} from '../utils/displayText.js'
const pager=usePagination({pageSize:20}),status=ref(''),keyword=ref(''),deleting=ref(null),dialog=ref(false),saving=ref(false);const form=reactive({id:null,title:'',content:'',status:'',version:0}),formErrors=reactive({title:'',content:''})
async function load(){await pager.load(({page,size})=>contentApi.adminAnnouncements({page,size,keyword:keyword.value.trim()||undefined,...(status.value?{status:status.value}:{})})).catch(()=>{})}function changeFilter(){pager.reset();load()}function changePageSize(){pager.reset();load()}
function createOpen(){Object.assign(form,{id:null,title:'',content:'',status:'DRAFT',version:0});Object.assign(formErrors,{title:'',content:''});dialog.value=true}async function editOpen(row){Object.assign(form,await contentApi.adminAnnouncement(row.id));Object.assign(formErrors,{title:'',content:''});dialog.value=true}
function validate(){formErrors.title=form.title.trim()?'':'标题必填';if(form.title.trim().length>200)formErrors.title='标题不能超过 200 字';formErrors.content=form.content.trim()?'':'正文必填';return !formErrors.title&&!formErrors.content}
async function save(){if(!validate())return;saving.value=true;try{if(!form.id) await contentApi.adminCreateAnnouncement({title:form.title.trim(),content:form.content.trim()});else await contentApi.adminPatchAnnouncement(form.id,{title:form.title.trim(),content:form.content.trim(),version:form.version});dialog.value=false;await load()}finally{saving.value=false}}
async function publish(row){await ElMessageBox.confirm('发布后公告将对公众可见','发布公告');await contentApi.adminPublishAnnouncement(row.id,row.version);ElMessage.success('已发布');await load()}async function withdraw(row){await ElMessageBox.confirm('撤回后不可重新发布','撤回公告');await contentApi.adminWithdrawAnnouncement(row.id,row.version);ElMessage.success('已撤回');await load()}async function remove(row){try{await ElMessageBox.confirm('删除后公告将从管理列表及公众页面移除，历史审计记录保留。','删除公告 · '+row.title,{type:'warning',confirmButtonText:'确认删除',cancelButtonText:'取消'});deleting.value=row.id;await contentApi.adminDeleteAnnouncement(row.id,row.version);ElMessage.success('公告已删除');pager.reset();await load()}catch(e){if(e!=='cancel'&&e!=='close'&&!e?.userMessage)ElMessage.error('删除失败，请刷新后重试')}finally{deleting.value=null}}
onMounted(load)
</script>
