<template>
  <PageHeader title="线索审核" subtitle="核实现场信息，让每一条求助得到回应"><el-button :loading="pager.loading.value" @click="load">刷新</el-button></PageHeader>
  <div class="toolbar"><el-select v-model="status" style="width:190px" @change="search"><el-option v-for="s in statuses" :key="s" :value="s" :label="displayText(s)"/></el-select><el-input v-model="keyword" class="search-field" clearable maxlength="100" placeholder="搜索地点、动物描述或联系方式" aria-label="搜索救助线索" @keyup.enter="search"/><el-button type="primary" @click="search">查询</el-button><el-button @click="resetFilters">重置</el-button></div>
  <ListError :message="pager.error.value" @retry="load"/>
  <div class="card table-card"><el-table :data="pager.rows.value" v-loading="pager.loading.value" row-key="id" empty-text="暂无线索"><el-table-column prop="id" label="编号" width="100"/><el-table-column prop="location" label="地点" min-width="180" show-overflow-tooltip/><el-table-column prop="foundTime" label="发现时间" width="190"/><el-table-column label="状态" width="160"><template #default="{row}"><StatusBadge :value="row.status"/></template></el-table-column><el-table-column label="操作" width="200" fixed="right"><template #default="{row}"><el-button size="small" @click="open(row)">详情</el-button><el-button v-if="row.status==='PENDING_REVIEW'" size="small" type="primary" @click="open(row,true)">审核</el-button></template></el-table-column></el-table></div>
  <el-pagination class="pager" background layout="sizes,prev,pager,next,total" :page-sizes="[10,20,50]" :total="pager.total.value" v-model:page-size="pager.size.value" v-model:current-page="pager.page.value" @size-change="changePageSize" @current-change="load"/>
  <el-dialog align-center destroy-on-close :close-on-click-modal="false" v-model="drawer" width="800px" title="救助线索详情">
    <div v-loading="detailLoading" class="detail-loading"><template v-if="detail"><div class="archive-row"><AuthImage v-if="detail.images?.[0]" class="archive-img" :src="detail.images[0].url" fallback="/assets/coffee-kitten.png"/><div><b>#{{detail.id}}</b><div>{{detail.location}}</div><StatusBadge :value="detail.status"/></div></div><el-descriptions :column="1" border style="margin-top:16px"><el-descriptions-item label="发现时间">{{detail.foundTime}}</el-descriptions-item><el-descriptions-item label="动物描述">{{detail.animalDescription}}</el-descriptions-item><el-descriptions-item label="现场情况">{{detail.sceneDescription||'—'}}</el-descriptions-item><el-descriptions-item label="联系方式">{{detail.contact}}</el-descriptions-item><el-descriptions-item v-if="detail.rejectReason" label="驳回原因">{{detail.rejectReason}}</el-descriptions-item></el-descriptions><div v-if="auditMode && detail.status==='PENDING_REVIEW'" class="card" style="margin-top:18px"><h3 class="section-title">审核决定</h3><el-radio-group v-model="audit.decision"><el-radio-button value="APPROVE">通过</el-radio-button><el-radio-button value="REJECT">驳回</el-radio-button></el-radio-group><el-input v-if="audit.decision==='REJECT'" v-model="audit.rejectReason" type="textarea" maxlength="500" show-word-limit style="margin-top:12px" placeholder="驳回原因必填"/><el-button type="primary" style="margin-top:12px" :loading="saving" @click="submitAudit">确认审核</el-button></div></template></div>
  </el-dialog>
</template>
<script setup>
import {useRoute} from 'vue-router'
const route=useRoute()
import {ref,reactive,onMounted} from 'vue';import {ElMessage} from '../plugins/message.js';import PageHeader from '../components/PageHeader.vue';import StatusBadge from '../components/StatusBadge.vue';import AuthImage from '../components/AuthImage.vue';import ListError from '../components/ListError.vue';import {clueApi} from '../api/index.js';import {usePagination} from '../composables/usePagination.js';import {displayText} from '../utils/displayText.js'
const statuses=['PENDING_REVIEW','WAITING_ACCEPT','REJECTED','WITHDRAWN','CONVERTED','CLOSED'];const status=ref(statuses.includes(String(route.query.status))?String(route.query.status):'PENDING_REVIEW'),keyword=ref(''),pager=usePagination({pageSize:20}),drawer=ref(false),detail=ref(null),detailLoading=ref(false),auditMode=ref(false),saving=ref(false);const audit=reactive({decision:'APPROVE',rejectReason:''})
async function load(){await pager.load(({page,size})=>clueApi.adminList({page,size,status:status.value,keyword:keyword.value.trim()||undefined})).catch(()=>{})}
function search(){pager.reset();load()}function resetFilters(){status.value='PENDING_REVIEW';keyword.value='';search()}function changePageSize(){pager.reset();load()}
async function open(row,mode=false){detail.value=null;drawer.value=true;detailLoading.value=true;auditMode.value=mode;audit.decision='APPROVE';audit.rejectReason='';try{detail.value=await clueApi.detail(row.id)}catch{drawer.value=false}finally{detailLoading.value=false}}
async function submitAudit(){if(audit.decision==='REJECT'&&!audit.rejectReason.trim()){ElMessage.warning('驳回原因必填');return}saving.value=true;try{await clueApi.audit(detail.value.id,audit.decision==='APPROVE'?{decision:'APPROVE'}:{decision:'REJECT',rejectReason:audit.rejectReason.trim()});ElMessage.success('审核完成');drawer.value=false;await load()}finally{saving.value=false}}
onMounted(load)
</script>
