<template>
  <PageHeader :title="role==='ADMIN'?'救助中心工作台':'我的救助工作台'" :subtitle="greeting"><el-button :loading="loading" @click="load">刷新</el-button></PageHeader>
  <ListError :message="loadError" @retry="load"/><p class="refresh-meta">{{lastLoadedAt?'更新于 '+lastLoadedAt:'正在同步工作台…'}}</p>
  <div v-if="role==='ADMIN'" class="work-metrics" v-loading="loading">
    <router-link to="/clues?status=PENDING_REVIEW"><span>待审核线索</span><b>{{count('rescueClues','PENDING_REVIEW')}}</b><small>查看审核队列 →</small></router-link>
    <router-link to="/adoptions?status=PENDING"><span>待审核领养</span><b>{{count('adoptionApplications','PENDING')}}</b><small>为它找到合适的新家 →</small></router-link>
    <router-link to="/tasks?status=IN_PROGRESS"><span>进行中救助</span><b>{{count('rescueTasks','IN_PROGRESS')}}</b><small>关注救助进展 →</small></router-link>
    <router-link to="/animals?status=AVAILABLE"><span>等待领养</span><b>{{count('animals','AVAILABLE')}}</b><small>查看动物档案 →</small></router-link>
  </div>
  <div v-else class="work-metrics" v-loading="loading"><router-link v-for="m in rescuerMetrics" :key="m.label" :to="m.to"><span>{{m.label}}</span><b>{{m.value}}</b><small>前往处理 →</small></router-link></div>
  <section class="work-queues"><div class="card"><h2>{{role==='ADMIN'?'待处理事项':'我的近期任务'}}</h2><template v-if="role==='ADMIN'"><router-link class="queue-link" to="/clues?status=PENDING_REVIEW"><span>线索审核</span><b>{{count('rescueClues','PENDING_REVIEW')}} 条 →</b></router-link><router-link class="queue-link" to="/adoptions?status=PENDING"><span>领养审核</span><b>{{count('adoptionApplications','PENDING')}} 条 →</b></router-link><router-link class="queue-link" to="/tasks?status=FAILED"><span>失败任务复核</span><b>{{count('rescueTasks','FAILED')}} 条 →</b></router-link><router-link class="queue-link" to="/users"><span>用户与救助资格管理</span><b>前往管理 →</b></router-link></template><template v-else><router-link v-for="t in tasks" :key="t.id" :to="'/tasks?status='+t.status" class="queue-link"><span>救助任务 #{{t.id}}</span><StatusBadge :value="t.status"/></router-link><el-empty v-if="!tasks.length&&!loading" description="还没有救助任务，从待接取线索开始吧"/></template></div><div class="card care-card"><p class="eyebrow">把善意落到每一步</p><h2>{{role==='ADMIN'?'让协作井然有序':'每次行动，都值得记录'}}</h2><p>{{role==='ADMIN'?'及时处理线索与领养申请，关注异常任务，让救助与领养顺畅衔接。':'接取任务后及时开始救助，记录现场进展；完成后为动物建立档案并持续关注健康。'}}</p><router-link :to="role==='ADMIN'?'/animals':'/tasks?tab=waiting'">{{role==='ADMIN'?'查看动物档案':'查看等待接取'}} →</router-link></div></section>
  <section class="recent-case-section"><div class="recent-heading"><div><p class="eyebrow">LIVE ARCHIVES · 平台档案</p><h2>最近照护的它们</h2></div><router-link to="/animals">查看全部档案 →</router-link></div><div v-if="recentAnimals.length" class="recent-cases"><router-link v-for="animal in recentAnimals" :key="animal.id" class="recent-case" to="/animals"><AuthImage :src="animal.coverImageUrl" fallback="/assets/pudding-cat-hero.png"/><div><span><StatusBadge :value="animal.status"/></span><h3>{{animal.name}}</h3><p>{{animal.healthCondition}}</p><small>{{animal.personality||'性格观察待救助人员补充'}}</small></div></router-link></div><el-empty v-else-if="!loading" description="暂无动物档案；完成救助并上传图片后会显示在这里"/></section>
  <template v-if="role==='ADMIN'">
    <section class="card trend-card"><div class="trend-header"><div><h2>救助与领养趋势</h2><p class="muted">按日统计完成的救助和成功领养，最多查看一年。</p></div><div class="date-controls"><el-date-picker v-model="range" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" :clearable="false" style="max-width:100%;width:270px"/><el-button :loading="trendLoading" @click="loadTrends">查询</el-button></div></div><p v-if="trendError" class="trend-error" role="alert">{{trendError}}</p><div class="legend"><span>● 救助成功</span><span>● 成功领养</span></div><div class="chart-scroll" v-loading="trendLoading"><div class="trend-chart" :style="{minWidth:Math.max(380,trends.length*42)+'px'}"><div v-for="p in trends" :key="p.date" class="trend-day" :aria-label="p.date+'，救助成功 '+p.rescueSuccessCount+'，成功领养 '+p.adoptionCount"><div class="column-pair"><div class="rescue-bar" :title="p.date+' 救助成功：'+p.rescueSuccessCount" :style="{height:barHeight(p.rescueSuccessCount)+'%'}"><span>{{p.rescueSuccessCount}}</span></div><div class="adopt-bar" :title="p.date+' 成功领养：'+p.adoptionCount" :style="{height:barHeight(p.adoptionCount)+'%'}"><span>{{p.adoptionCount}}</span></div></div><small>{{p.date.slice(5)}}</small></div></div></div><el-empty v-if="!trends.length&&!trendLoading&&!trendError" description="请选择时间范围"/></section>
    <section class="status-grid"><div v-for="g in groups" :key="g.key" class="card"><h2>{{g.title}}</h2><router-link v-for="(value,key) in stats[g.key]||{}" :key="key" :to="g.path+'?status='+key" class="status-line"><span>{{displayText(key)}}</span><b>{{value}}</b></router-link></div></section>
  </template>
</template>
<script setup>
import {ref,computed,onMounted} from 'vue'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'
import AuthImage from '../components/AuthImage.vue'
import ListError from '../components/ListError.vue'
import {adminApi,rescueApi,animalApi,followupApi,clueApi} from '../api/index.js'
import {useAuth} from '../store/auth.js'
import {displayText} from '../utils/displayText.js'
import {validTrendRange,chartPercent} from '../utils/dashboard.js'
const auth=useAuth(),role=computed(()=>auth.state.user?.roleCode),greeting=computed(()=> '您好，'+(auth.state.user?.nickname||auth.state.user?.account||'宠链成员')+'。今天也一起为它们做点事。')
const stats=ref({}),trends=ref([]),tasks=ref([]),recentAnimals=ref([]),rescuerMetrics=ref([]),loading=ref(false),loadError=ref(''),lastLoadedAt=ref(''),trendLoading=ref(false),trendError=ref('')
const count=(group,key)=>stats.value?.[group]?.[key]??0
const shanghaiDate=date=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)
const range=ref([shanghaiDate(new Date(Date.now()-6*86400000)),shanghaiDate(new Date())])
const groups=[{key:'rescueClues',title:'线索状态',path:'/clues'},{key:'rescueTasks',title:'任务状态',path:'/tasks'},{key:'animals',title:'动物状态',path:'/animals'},{key:'adoptionApplications',title:'申请状态',path:'/adoptions'}]
const peak=computed(()=>Math.max(1,...trends.value.flatMap(p=>[p.rescueSuccessCount,p.adoptionCount])))
const barHeight=n=>chartPercent(n,peak.value)
let trendSeq=0
async function loadTrends(){if(!validTrendRange(range.value)){trendError.value='请选择有效的起止日期，范围不能超过 366 天';return}const id=++trendSeq;trendLoading.value=true;trendError.value='';try{const data=await adminApi.statsTrends({from:range.value[0],to:range.value[1],granularity:'DAY'});if(id===trendSeq)trends.value=data.points||[]}catch(e){if(id===trendSeq)trendError.value=e?.userMessage||'趋势加载失败'}finally{if(id===trendSeq)trendLoading.value=false}}
async function load(){if(loading.value)return;loading.value=true;loadError.value='';try{if(role.value==='ADMIN'){const [overview,animals]=await Promise.all([adminApi.statsOverview(),adminApi.animals({page:1,size:3})]);stats.value=overview;recentAnimals.value=animals.records||[];await loadTrends()}else{const [waiting,start,progress,animals,followups,recent]=await Promise.all([clueApi.waiting({page:1,size:1}),rescueApi.mine({page:1,size:1,status:'WAITING_START'}),rescueApi.mine({page:1,size:1,status:'IN_PROGRESS'}),animalApi.responsible({page:1,size:3}),followupApi.rescuerList({page:1,size:1}),rescueApi.mine({page:1,size:5})]);tasks.value=recent.records||[];recentAnimals.value=animals.records||[];rescuerMetrics.value=[{label:'等待接取',value:waiting.total,to:'/tasks?tab=waiting'},{label:'我的待开始',value:start.total,to:'/tasks?status=WAITING_START'},{label:'我的进行中',value:progress.total,to:'/tasks?status=IN_PROGRESS'},{label:'负责动物',value:animals.total,to:'/animals'},{label:'负责动物回访',value:followups.total,to:'/followups'}]}lastLoadedAt.value=new Date().toLocaleString('zh-CN')}catch(e){loadError.value=e?.userMessage||'工作台加载失败，请重试'}finally{loading.value=false}}
onMounted(load)
</script>
<style scoped>
.work-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:18px;margin:22px 0}.work-metrics>a{display:flex;flex-direction:column;gap:14px;padding:23px;background:#fffdf8;border:1px solid #dedfd2;border-radius:16px;text-decoration:none;color:var(--ink)}.work-metrics>a:first-child{background:#1b463b;color:#fff8e2}.work-metrics b{font-size:42px;line-height:1}.work-metrics span{font-size:14px}.work-metrics small{font-size:11px;opacity:.7}.work-queues{display:grid;grid-template-columns:1.4fr 1fr;gap:20px;margin-bottom:24px}.card h2{font-size:19px;margin:0 0 18px}.queue-link,.status-line{display:flex;justify-content:space-between;align-items:center;gap:15px;padding:16px 0;border-bottom:1px solid #e3e3d8;color:var(--ink);text-decoration:none;font-size:13px}.queue-link:hover,.status-line:hover{color:var(--orange)}.care-card{background:#e5ebda;padding:30px}.care-card h2{font-size:28px;margin-top:25px}.care-card p{line-height:1.9;font-size:14px}.care-card a{display:inline-block;margin-top:20px;color:var(--ink)}.trend-header{display:flex;justify-content:space-between;align-items:start;gap:20px}.date-controls{display:flex;gap:8px;flex-wrap:wrap}.legend{display:flex;gap:20px;font-size:12px;margin:20px 0}.legend span:first-child{color:#45877b}.legend span:last-child{color:#cb7855}.chart-scroll{overflow-x:auto;padding:25px 0 5px}.trend-chart{display:flex;gap:12px;height:205px}.trend-day{flex:1;min-width:28px;text-align:center}.column-pair{display:flex;align-items:end;justify-content:center;gap:6px;height:175px;border-bottom:1px solid #d5dbce;padding:0 4px}.column-pair>div{width:38%;max-width:32px;position:relative;border-radius:5px 5px 0 0}.rescue-bar{background:#73a397}.adopt-bar{background:#dc9779}.column-pair span{position:absolute;bottom:100%;left:50%;transform:translateX(-50%);font-size:10px;padding-bottom:5px}.trend-day small{display:block;font-size:10px;margin-top:12px}.status-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-top:24px}.trend-error{color:#a13728}.trend-header .muted{font-size:12px}@media(max-width:1000px){.trend-header{flex-direction:column}.work-queues{grid-template-columns:1fr}}@media(max-width:600px){.status-grid{grid-template-columns:1fr}.work-metrics{grid-template-columns:1fr 1fr}}
.recent-case-section{margin:26px 0 30px;padding:28px;border:1px solid #dedfd2;border-radius:18px;background:#fffdf8}.recent-heading{display:flex;align-items:end;justify-content:space-between;gap:18px;margin-bottom:18px}.recent-heading h2{margin:5px 0 0}.recent-heading a{color:var(--ink);font-size:13px}.recent-cases{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.recent-case{overflow:hidden;border:1px solid #dde0d3;border-radius:14px;background:#f3f1e8;color:var(--ink);text-decoration:none}.recent-case :deep(img){display:block;width:100%;height:150px;object-fit:cover}.recent-case>div{padding:18px}.recent-case h3{margin:12px 0 7px;font-size:20px}.recent-case p{min-height:42px;margin:0;color:#53675f;font-size:12px;line-height:1.7}.recent-case small{display:block;margin-top:13px;padding-top:12px;border-top:1px solid #d8dcce;color:#78867f;line-height:1.55}@media(max-width:900px){.recent-cases{grid-template-columns:1fr}.recent-case{display:grid;grid-template-columns:180px 1fr}.recent-case :deep(img){height:100%;min-height:160px}}@media(max-width:560px){.recent-case{display:block}.recent-heading{align-items:start;flex-direction:column}}
</style>
