<template>
  <PageHeader title="回访记录" :subtitle="role==='ADMIN'?'管理员查看全部回访':'救助人员查看负责动物回访'"><el-button :loading="pager.loading.value" @click="load">刷新</el-button></PageHeader>
  <div class="toolbar"><el-input v-model="animalId" class="search-field" clearable placeholder="动物编号" aria-label="按动物编号筛选回访" @keyup.enter="search"/><el-input v-if="role==='ADMIN'" v-model="userId" class="search-field" clearable placeholder="提交人编号" aria-label="按提交人筛选回访" @keyup.enter="search"/><el-button type="primary" @click="search">查询</el-button><el-button @click="animalId='';userId='';search()">重置</el-button></div>
  <ListError :message="pager.error.value" @retry="load"/>
  <div class="card table-card"><el-table :data="pager.rows.value" v-loading="pager.loading.value" empty-text="暂无回访记录"><el-table-column label="近况照片" width="100"><template #default="{row}"><AuthImage class="followup-thumb" :src="row.images?.[0]?.url" fallback="/assets/pudding-cat-hero.png"/></template></el-table-column><el-table-column prop="id" label="回访编号" width="100"/><el-table-column prop="adoptionRecordId" label="领养记录" width="120"/><el-table-column prop="submitterId" label="提交人" width="110"/><el-table-column prop="content" label="生活情况"/><el-table-column prop="healthCondition" label="健康情况"/><el-table-column prop="createdAt" label="时间" width="190"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button size="small" @click="open(row)">详情</el-button></template></el-table-column></el-table></div>
  <el-pagination class="pager" background layout="sizes,prev,pager,next,total" :page-sizes="[10,20,50]" :total="pager.total.value" v-model:page-size="pager.size.value" v-model:current-page="pager.page.value" @size-change="changePageSize" @current-change="load"/>
  <el-dialog align-center destroy-on-close :close-on-click-modal="false" v-model="drawer" width="760px" title="回访详情"><div v-loading="detailLoading" class="detail-loading"><template v-if="detail"><div class="reason"><b>回访 #{{detail.id}}</b><div>{{detail.content||'—'}}</div><div>健康：{{detail.healthCondition||'—'}}</div><div class="muted">{{detail.createdAt}}</div></div><div class="photos"><AuthImage v-for="img in detail.images||[]" :key="img.id" :src="img.url"/></div></template></div></el-dialog>
</template>
<script setup>
import {ElMessage} from '../plugins/message.js'
import{ref,computed,onMounted}from'vue';import PageHeader from'../components/PageHeader.vue';import AuthImage from'../components/AuthImage.vue';import ListError from '../components/ListError.vue';import{followupApi}from'../api/index.js';import{useAuth}from'../store/auth.js';import {usePagination} from '../composables/usePagination.js'
const role=computed(()=>useAuth().state.user?.roleCode),pager=usePagination({pageSize:20}),drawer=ref(false),detail=ref(null),detailLoading=ref(false),animalId=ref(''),userId=ref('')
async function load(){await pager.load(({page,size})=>role.value==='ADMIN'?followupApi.adminList({page,size,animalId:animalId.value||undefined,userId:userId.value||undefined}):followupApi.rescuerList({page,size,animalId:animalId.value||undefined})).catch(()=>{})}
function search(){if([animalId.value,userId.value].some(v=>v&&!/^[1-9]\d*$/.test(v))){ElMessage.warning('请输入有效的正整数编号');return}pager.reset();load()}
function changePageSize(){pager.reset();load()}async function open(row){detail.value=null;drawer.value=true;detailLoading.value=true;try{detail.value=await followupApi.detail(row.id)}catch{drawer.value=false}finally{detailLoading.value=false}}onMounted(load)
</script>
<style scoped>.followup-thumb{width:68px;height:50px;border-radius:9px;object-fit:cover}.photos{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:16px}.photos img{width:100%;height:118px;object-fit:cover;border:1px solid rgba(216,209,195,.86);border-radius:12px;box-shadow:0 8px 18px rgba(23,61,57,.08)}</style>
