<template><main class="registration"><router-link class="back-home" to="/">← 宠链首页</router-link><section class="register-card"><p class="overline">从一次相遇开始</p><h1>加入宠链</h1><p class="muted">发现伙伴、分享线索，让每一份善意都有回响。</p><el-form label-position="top" @submit.prevent="submit"><el-alert v-if="error" :title="error" type="error" :closable="false" show-icon/><el-form-item label="账号" :error="errors.account"><el-input v-model="form.account" autocomplete="username" maxlength="50" placeholder="4～50 位字母、数字或下划线"/></el-form-item><el-form-item label="昵称（选填）" :error="errors.nickname"><el-input v-model="form.nickname" maxlength="50" placeholder="希望我们如何称呼你"/></el-form-item><el-form-item label="密码" :error="errors.password"><el-input v-model="form.password" type="password" show-password autocomplete="new-password" placeholder="8～64 个字符"/></el-form-item><el-form-item label="确认密码" :error="errors.confirm"><el-input v-model="form.confirm" type="password" show-password autocomplete="new-password"/></el-form-item><el-form-item label="手机号（选填）" :error="errors.phone"><el-input v-model="form.phone" autocomplete="tel" maxlength="11"/></el-form-item><el-button type="primary" native-type="submit" :loading="busy" class="wide">创建账号</el-button></el-form><p class="footnote">注册后即可使用公众服务；救助人员资格由管理员审核调整。</p><p>已有账号？<router-link to="/login">立即登录 →</router-link></p></section></main></template>
<script setup>
import {reactive,ref} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessage} from '../plugins/message.js'
import {authApi} from '../api/index.js'
import {validateRegistration} from '../utils/registration.js'
const router=useRouter(),form=reactive({account:'',nickname:'',password:'',confirm:'',phone:''}),errors=reactive({}),error=ref(''),busy=ref(false)
async function submit(){if(busy.value)return;Object.assign(errors,validateRegistration(form));if(Object.values(errors).some(Boolean))return;busy.value=true;error.value='';try{await authApi.register({account:form.account.trim(),password:form.password,nickname:form.nickname.trim()||undefined,phone:form.phone.trim()||null});ElMessage.success('注册成功，请登录');router.replace({path:'/login',query:{account:form.account.trim(),registered:'1'}})}catch(e){error.value=e?.userMessage||'注册失败，请稍后重试'}finally{busy.value=false}}
</script>
<style scoped>.registration{min-height:100vh;padding:30px 20px 60px;background:#f7f5ed}.back-home{color:#204a3f;text-decoration:none}.register-card{max-width:480px;margin:24px auto;background:white;border:1px solid #e1e6d8;border-radius:24px;padding:36px;box-shadow:0 18px 60px #173d3910}.register-card h1{font-size:32px;margin:12px 0}.overline{color:#997443;font-size:12px;letter-spacing:2px}.register-card .el-form{margin-top:26px}.wide{width:100%;height:44px}.footnote{font-size:12px;color:#64746c;line-height:1.8}.register-card a{color:#246955}.register-card .el-alert{margin-bottom:15px}@media(max-width:500px){.register-card{padding:24px}}</style>
