<template>
  <PageHeader title="救助任务" :subtitle="role==='ADMIN'?'第三模块 · 管理员监管与异常处理':'第三模块 · 待接取线索与本人任务'"><el-button :loading="pager.loading.value || waitingPager.loading.value" @click="refreshAll">刷新</el-button></PageHeader>
  <template v-if="role==='RESCUER'">
    <div class="section-heading"><div><h3 class="section-title">等待接取</h3><div class="muted">管理员审核通过的救助线索会出现在这里</div></div><el-button :loading="waitingPager.loading.value" @click="loadWaiting">刷新待接取</el-button></div>
    <ListError :message="waitingPager.error.value" @retry="loadWaiting"/>
    <div class="card table-card"><el-table :data="waitingPager.rows.value" v-loading="waitingPager.loading.value" row-key="id" empty-text="暂无待接取线索"><el-table-column prop="id" label="线索" width="100"/><el-table-column prop="location" label="发现地点" min-width="180"/><el-table-column prop="animalDescription" label="动物描述" min-width="240" show-overflow-tooltip/><el-table-column prop="foundTime" label="发现时间" width="190"/><el-table-column label="状态" width="120"><template #default="{row}"><StatusBadge :value="row.status"/></template></el-table-column><el-table-column label="操作" width="130" fixed="right"><template #default="{row}"><el-button size="small" type="primary" :loading="waitingActionId===row.id" @click="acceptWaiting(row)">接取救助</el-button></template></el-table-column></el-table></div>
    <el-pagination class="pager" background layout="sizes,prev,pager,next,total" :page-sizes="[10,20,50]" :total="waitingPager.total.value" v-model:page-size="waitingPager.size.value" v-model:current-page="waitingPager.page.value" @size-change="changeWaitingPageSize" @current-change="loadWaiting"/>
    <div class="section-heading task-section"><div><h3 class="section-title">我的任务</h3><div class="muted">已经接取并由当前救助人员负责的任务</div></div></div>
  </template>
  <div class="toolbar"><el-select v-model="status" clearable placeholder="全部状态" style="width:190px" @change="changeFilter"><el-option v-for="s in statuses" :key="s" :label="displayText(s)" :value="s"/></el-select></div>
  <ListError :message="pager.error.value" @retry="load"/>
  <div class="card table-card"><el-table :data="pager.rows.value" v-loading="pager.loading.value" row-key="id" empty-text="暂无救助任务"><el-table-column prop="id" label="任务" width="100"/><el-table-column prop="clueId" label="线索" width="100"/><el-table-column v-if="role==='ADMIN'" prop="rescuerId" label="救助人员" width="120"/><el-table-column label="状态" width="150"><template #default="{row}"><StatusBadge :value="row.status"/></template></el-table-column><el-table-column prop="startedAt" label="开始时间" min-width="180"/><el-table-column prop="finishedAt" label="完成时间" min-width="180"/><el-table-column label="操作" width="280" fixed="right"><template #default="{row}"><el-button size="small" @click="open(row)">详情</el-button><template v-if="role==='ADMIN'"><el-button v-if="['WAITING_START','IN_PROGRESS'].includes(row.status)" size="small" type="danger" plain :loading="actionId===row.id" @click="cancel(row)">取消</el-button><el-button v-if="row.status==='FAILED'" size="small" type="warning" plain :loading="actionId===row.id" @click="resolve(row)">失败处理</el-button></template><template v-else><el-button v-if="row.status==='WAITING_START'" size="small" type="primary" :loading="actionId===row.id" @click="start(row)">开始救助</el-button></template></template></el-table-column></el-table></div>
  <el-pagination class="pager" background layout="sizes,prev,pager,next,total" :page-sizes="[10,20,50]" :total="pager.total.value" v-model:page-size="pager.size.value" v-model:current-page="pager.page.value" @size-change="changePageSize" @current-change="load"/>
  <el-drawer v-model="drawer" size="650px" title="救助任务详情"><div v-loading="detailLoading"><template v-if="detail"><div class="archive-row"><img class="archive-img" src="/assets/ahei-black-dog.png" alt="救助任务占位图"/><div><b>任务 #{{detail.id}}</b><div>线索 #{{detail.clueId}}</div><StatusBadge :value="detail.status"/></div></div><el-descriptions :column="1" border style="margin-top:16px"><el-descriptions-item label="失败原因">{{detail.failureReason||'—'}}</el-descriptions-item><el-descriptions-item label="取消原因">{{detail.cancelReason||'—'}}</el-descriptions-item></el-descriptions><h3 class="section-title" style="margin-top:20px">救助记录</h3><div v-if="!records.length" class="muted">暂无过程记录</div><div v-for="r in records" :key="r.id" class="reason" style="margin:8px 0"><b>#{{r.id}}</b> {{r.content}}<div class="muted">{{r.createdAt}}</div></div><template v-if="role==='RESCUER'&&detail.status==='IN_PROGRESS'"><el-input v-model="recordText" type="textarea" maxlength="2000" show-word-limit placeholder="追加救助过程记录"/><el-button style="margin-top:8px" :loading="recordSaving" @click="addRecord">保存记录</el-button><div class="action-row" style="margin-top:16px"><el-button type="danger" plain :loading="resultSaving" @click="submitFailure">提交救助失败</el-button><el-button type="primary" :disabled="resultSaving" @click="successDialog=true">提交救助成功并建档</el-button></div></template></template></div></el-drawer>
  <el-dialog v-model="successDialog" title="救助成功 · 创建动物档案" width="680px"><div class="reason">救助成功时至少创建 1 个动物档案；本次请求的图片标识合计最多 9 个且不得重复。</div><div v-for="(a,i) in animals" :key="i" class="card" style="margin-bottom:10px"><div class="form-grid"><el-input v-model="a.name" maxlength="100" placeholder="名称*"/><el-input v-model="a.species" maxlength="50" placeholder="种类，例如猫*"/><el-select v-model="a.sex"><el-option label="公" value="MALE"/><el-option label="母" value="FEMALE"/><el-option label="未知" value="UNKNOWN"/></el-select><el-input-number v-model="a.estimatedAgeMonths" :min="0" :max="65535"/><el-input v-model="a.color" maxlength="100" placeholder="毛色"/><el-input v-model="a.healthCondition" maxlength="1000" placeholder="当前健康情况*"/><el-input class="full" v-model="a.initialHealthRecord" type="textarea" maxlength="2000" show-word-limit placeholder="初始健康记录（可选）"/><div class="full"><ImageTokenUploader v-model="a.imageTokens" /></div></div><el-button v-if="animals.length>1" type="danger" text @click="animals.splice(i,1)">删除动物档案</el-button></div><el-alert v-if="successError" :title="successError" type="error" :closable="false" show-icon/><el-button style="margin-top:10px" @click="animals.push(newAnimal())">+ 添加动物档案</el-button><template #footer><el-button @click="successDialog=false">取消</el-button><el-button type="primary" :loading="resultSaving" @click="submitSuccess">提交救助成功</el-button></template></el-dialog>
</template>
<script setup>
import {ref,computed,onMounted} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import PageHeader from '../components/PageHeader.vue';import StatusBadge from '../components/StatusBadge.vue';import ImageTokenUploader from '../components/ImageTokenUploader.vue';import ListError from '../components/ListError.vue';import {clueApi,rescueApi,adminApi} from '../api/index.js';import {useAuth} from '../store/auth.js';import {usePagination} from '../composables/usePagination.js';import {failureResolutionFromDialog} from '../domain/rescueResolutionPolicy.js';import {displayText} from '../utils/displayText.js'
const role=computed(()=>useAuth().state.user?.roleCode);const statuses=['WAITING_START','IN_PROGRESS','SUCCESS','FAILED','CANCELED'];const status=ref(''),pager=usePagination({pageSize:20}),waitingPager=usePagination({pageSize:20}),drawer=ref(false),detail=ref(null),records=ref([]),recordText=ref(''),successDialog=ref(false),detailLoading=ref(false),recordSaving=ref(false),resultSaving=ref(false),actionId=ref(null),waitingActionId=ref(null),successError=ref('');const newAnimal=()=>({name:'',species:'CAT',sex:'UNKNOWN',estimatedAgeMonths:null,color:'',healthCondition:'',initialHealthRecord:'',imageTokens:[]});const animals=ref([newAnimal()])
async function load(){await pager.load(({page,size})=>{const params={page,size,...(status.value?{status:status.value}:{})};return role.value==='ADMIN'?adminApi.rescueTasks(params):rescueApi.mine(params)}).catch(()=>{})}function changeFilter(){pager.reset();load()}function changePageSize(){pager.reset();load()}
async function loadWaiting(){if(role.value!=='RESCUER')return;await waitingPager.load(({page,size})=>clueApi.waiting({page,size})).catch(()=>{})}
async function refreshAll(){await Promise.all([load(),loadWaiting()])}
function changeWaitingPageSize(){waitingPager.reset();loadWaiting()}
async function acceptWaiting(row){waitingActionId.value=row.id;try{await rescueApi.accept(row.id);ElMessage.success('已接取，任务已进入待开始状态');waitingPager.reset();pager.reset();await refreshAll()}finally{waitingActionId.value=null}}
async function open(row){detailLoading.value=true;try{detail.value=await rescueApi.detail(row.id);records.value=await rescueApi.records(row.id);drawer.value=true}finally{detailLoading.value=false}}
async function start(row){actionId.value=row.id;try{await rescueApi.start(row.id);ElMessage.success('任务已开始');await load()}finally{actionId.value=null}}
async function addRecord(){const content=recordText.value.trim();if(!content){ElMessage.warning('救助记录不能为空');return}if(content.length>2000){ElMessage.warning('救助记录不能超过 2000 字');return}recordSaving.value=true;try{await rescueApi.addRecord(detail.value.id,{content});recordText.value='';records.value=await rescueApi.records(detail.value.id)}finally{recordSaving.value=false}}
async function submitFailure(){const {value}=await ElMessageBox.prompt('填写失败原因','提交救助失败',{inputType:'textarea',inputValidator:v=>{const x=v?.trim()||'';return (!!x&&x.length<=500)||'失败原因需为 1～500 字'}});resultSaving.value=true;try{await rescueApi.submitResult(detail.value.id,{result:'FAILED',failureReason:value.trim()});drawer.value=false;await load()}finally{resultSaving.value=false}}
function validateSuccess(){successError.value='';if(!animals.value.length){successError.value='至少创建 1 个动物档案';return false}let total=0;const seen=new Set();for(const a of animals.value){if(!a.name.trim()||a.name.trim().length>100||!a.species.trim()||a.species.trim().length>50||!a.healthCondition.trim()||a.healthCondition.trim().length>1000){successError.value='请检查动物的名称、种类与健康情况必填项及长度';return false}total+=a.imageTokens.length;for(const token of a.imageTokens){if(seen.has(token)){successError.value='本次救助成功请求中图片标识不能重复';return false}seen.add(token)}}if(total>9){successError.value='所有动物图片合计最多 9 张';return false}return true}
async function submitSuccess(){if(!validateSuccess())return;resultSaving.value=true;try{await rescueApi.submitResult(detail.value.id,{result:'SUCCESS',animals:animals.value.map(a=>({...a,name:a.name.trim(),species:a.species.trim(),healthCondition:a.healthCondition.trim(),initialHealthRecord:a.initialHealthRecord?.trim()||null,color:a.color?.trim()||null}))});successDialog.value=false;drawer.value=false;animals.value=[newAnimal()];ElMessage.success('救助成功并完成建档');await load()}finally{resultSaving.value=false}}
async function cancel(row){const {value}=await ElMessageBox.prompt('取消原因','管理员取消异常任务',{inputType:'textarea',inputValidator:v=>{const x=v?.trim()||'';return (!!x&&x.length<=500)||'取消原因需为 1～500 字'}});actionId.value=row.id;try{await rescueApi.adminCancel(row.id,{cancelReason:value.trim()});await load()}finally{actionId.value=null}}
async function resolve(row){let dialogAction='close';try{await ElMessageBox.confirm('确认重新开放线索；如需关闭线索，请点击“选择关闭”。关闭弹窗或按退出键将取消操作。','救助失败任务处理',{confirmButtonText:'重新开放',cancelButtonText:'选择关闭',distinguishCancelAndClose:true,closeOnPressEscape:true,closeOnClickModal:true});dialogAction='confirm'}catch(reason){dialogAction=reason==='cancel'?'cancel':'close'}const action=failureResolutionFromDialog(dialogAction);if(!action)return;let promptResult;try{promptResult=await ElMessageBox.prompt('处理原因',action==='REOPEN'?'重新开放线索':'关闭线索',{inputType:'textarea',inputValidator:v=>{const x=v?.trim()||'';return (!!x&&x.length<=500)||'处理原因需为 1～500 字'}})}catch{return}actionId.value=row.id;try{await rescueApi.failureResolution(row.id,{action,resolutionReason:promptResult.value.trim()});await load()}finally{actionId.value=null}}
onMounted(refreshAll)
</script>
<style scoped>
.section-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:4px 0 14px}.section-heading .section-title{margin:0 0 4px}.task-section{margin-top:28px}
</style>
