<template>
  <PageHeader title="用户与救助人员" subtitle="管理账户状态与救助资格，让每一份责任清晰可追溯"><el-button :loading="pager.loading.value" @click="load">刷新列表</el-button></PageHeader>
  <div class="user-intro"><div><b>{{pager.total.value}}</b><span>个符合条件的账户</span></div><p>新注册用户自动出现在这里。角色调整保留历史记录；有活动救助任务时不能降级。</p></div>
  <div class="toolbar"><el-input v-model="keyword" placeholder="搜索账号或昵称" aria-label="搜索账号或昵称" clearable style="width:240px" @keyup.enter="search"/><el-select v-model="role" clearable placeholder="全部角色" aria-label="角色筛选" style="width:150px" @change="search"><el-option v-for="r in ['USER','RESCUER','ADMIN']" :key="r" :label="displayText(r)" :value="r"/></el-select><el-select v-model="status" clearable placeholder="全部状态" aria-label="状态筛选" style="width:150px" @change="search"><el-option label="已启用" value="ENABLED"/><el-option label="已禁用" value="DISABLED"/></el-select><el-button @click="search">查询</el-button><el-button @click="reset">重置</el-button></div>
  <ListError :message="pager.error.value" @retry="load"/><el-alert v-if="actionError" :title="actionError" type="error" :closable="false" show-icon/>
  <div class="card table-card"><el-table :data="pager.rows.value" row-key="id" v-loading="pager.loading.value" empty-text="没有符合条件的用户"><el-table-column prop="account" label="账号" min-width="140"/><el-table-column prop="nickname" label="昵称" min-width="130" show-overflow-tooltip/><el-table-column label="角色" width="120"><template #default="{row}">{{displayText(row.roleCode)}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><StatusBadge :value="row.status"/></template></el-table-column><el-table-column label="注册时间" min-width="170"><template #default="{row}">{{date(row.createdAt)}}</template></el-table-column><el-table-column label="账户操作" width="440" fixed="right"><template #default="{row}"><el-button size="small" :disabled="busy" @click="open(row)">详情</el-button><el-button v-if="row.status==='ENABLED'" size="small" type="danger" plain :disabled="busy||String(row.id)===String(auth.state.user?.id)" @click="toggle(row)">禁用</el-button><el-button v-else size="small" type="success" plain :disabled="busy" @click="toggle(row)">启用</el-button><el-button v-if="row.roleCode==='USER'" size="small" type="primary" plain :disabled="busy" @click="changeRole(row,'RESCUER')">晋升救援人员</el-button><el-button v-if="row.roleCode==='RESCUER'" size="small" type="warning" plain :disabled="busy" @click="changeRole(row,'USER')">降为普通用户</el-button><el-button v-if="row.roleCode!=='ADMIN'" size="small" type="danger" plain :disabled="busy" @click="deleteUser(row)">删除</el-button></template></el-table-column></el-table></div>
  <el-pagination class="pager" background layout="sizes,prev,pager,next,total" :page-sizes="[10,20,50]" :total="pager.total.value" v-model:page-size="pager.size.value" v-model:current-page="pager.page.value" @size-change="search" @current-change="load"/>
  <el-dialog align-center destroy-on-close :close-on-click-modal="false" v-model="drawer" title="用户详情" width="680px"><template v-if="detail"><el-descriptions :column="1" border><el-descriptions-item label="账号">{{detail.account}}</el-descriptions-item><el-descriptions-item label="昵称">{{detail.nickname}}</el-descriptions-item><el-descriptions-item label="手机号">{{detail.phone||'未填写'}}</el-descriptions-item><el-descriptions-item label="角色">{{displayText(detail.roleCode)}}</el-descriptions-item><el-descriptions-item label="状态">{{displayText(detail.status)}}</el-descriptions-item><el-descriptions-item label="注册时间">{{date(detail.createdAt)}}</el-descriptions-item><el-descriptions-item label="最近更新">{{date(detail.updatedAt)}}</el-descriptions-item></el-descriptions><h3>参与记录</h3><div v-if="detail.statistics" class="user-counts"><div v-for="(v,k) in detail.statistics" :key="k"><span>{{displayText(k)}}</span><b>{{v}}</b></div></div><p class="muted">角色调整不会改变该用户历史线索、救助、领养及回访的归属。降级后的动物档案由管理员继续维护。</p></template></el-dialog>
</template>
<script setup>
import {ref,onMounted} from 'vue'
import {ElMessage} from '../plugins/message.js'
import {ElMessageBox} from '../plugins/messageBox.js'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'
import ListError from '../components/ListError.vue'
import {adminApi} from '../api/index.js'
import {usePagination} from '../composables/usePagination.js'
import {displayText} from '../utils/displayText.js'
import {useAuth} from '../store/auth.js'
const auth=useAuth(),pager=usePagination({pageSize:20}),keyword=ref(''),role=ref(''),status=ref(''),drawer=ref(false),detail=ref(null),busy=ref(false),actionError=ref('')
const date=d=>d?new Date(d).toLocaleString('zh-CN'):'—'
async function load(){await pager.load(({page,size})=>adminApi.users({page,size,keyword:keyword.value.trim()||undefined,roleCode:role.value||undefined,status:status.value||undefined})).catch(()=>{})}
function search(){pager.reset();load()}function reset(){keyword.value='';role.value='';status.value='';search()}
async function perform(action){if(busy.value)return;busy.value=true;actionError.value='';try{await action()}catch(e){if(e!=='cancel'&&e!=='close')actionError.value=e?.userMessage||'操作失败，请刷新后重试'}finally{busy.value=false}}
function open(row){perform(async()=>{detail.value=await adminApi.user(row.id);drawer.value=true})}
function toggle(row){perform(async()=>{const disabling=row.status==='ENABLED';await ElMessageBox.confirm(disabling?'禁用后该账号将无法继续访问受保护功能，已有业务记录会保留。':'启用后该账号可以恢复使用。',disabling?'禁用 '+row.account:'启用 '+row.account,{confirmButtonText:'确认',cancelButtonText:'取消'});await (disabling?adminApi.disableUser(row.id):adminApi.enableUser(row.id));ElMessage.success('账户状态已更新');await load()})}
function changeRole(row,target){perform(async()=>{const demote=target==='USER';const {value}=await ElMessageBox.prompt(demote?'有待开始或进行中任务时不能降级。历史数据保留，后续动物照护由管理员承接。请填写调整原因：':'请确认该用户具备救助资格，并填写调整原因：',demote?'降为普通用户 · '+row.account:'晋升救援人员 · '+row.account,{confirmButtonText:'确认调整',cancelButtonText:'取消',inputType:'textarea',inputValidator:v=>!!v?.trim()&&v.trim().length<=500||'请填写 1～500 字原因'});await adminApi.changeRole(row.id,{roleCode:target,reason:value.trim()});ElMessage.success('角色已更新');await load()})}
function deleteUser(row){perform(async()=>{await ElMessageBox.confirm('删除后该用户将无法登录，并从管理列表移除。历史救助、领养及回访记录保留，账号不可重复注册；有未完成救助任务时不能删除。','删除用户 · '+row.account,{type:'warning',confirmButtonText:'确认删除',cancelButtonText:'取消'});await adminApi.deleteUser(row.id);ElMessage.success('用户已删除');pager.reset();await load()})}
onMounted(load)
</script>
<style scoped>.user-intro{display:flex;gap:30px;align-items:center;margin:24px 0;padding:22px;background:#e8eee1;border-radius:16px}.user-intro b{font-size:32px;margin-right:12px}.user-intro span,.user-intro p{font-size:13px;line-height:1.8;color:#5e7264}.user-counts{display:grid;grid-template-columns:1fr 1fr;gap:12px}.user-counts>div{padding:18px;background:#f3f5ed;border-radius:12px}.user-counts span{font-size:12px;display:block}.user-counts b{font-size:26px;display:block;margin-top:8px}@media(max-width:700px){.user-intro{display:block}}</style>
