<template>
  <PageHeader title="用户管理" subtitle="第八模块 · 启用、禁用与普通用户晋升救助人员"><el-button :loading="pager.loading.value" @click="load">刷新</el-button></PageHeader>
  <div class="toolbar"><el-input v-model="keyword" placeholder="账号 / 昵称" clearable style="width:240px" @keyup.enter="search"/><el-select v-model="role" clearable placeholder="全部角色" style="width:160px" @change="search"><el-option v-for="r in ['USER','RESCUER','ADMIN']" :key="r" :label="displayText(r)" :value="r"/></el-select><el-button @click="search">查询</el-button></div>
  <ListError :message="pager.error.value" @retry="load"/>
  <div class="card table-card"><el-table :data="pager.rows.value" v-loading="pager.loading.value" empty-text="暂无用户"><el-table-column prop="id" label="编号" width="90"/><el-table-column prop="account" label="账号"/><el-table-column prop="nickname" label="昵称"/><el-table-column label="角色" width="120"><template #default="{row}">{{displayText(row.roleCode)}}</template></el-table-column><el-table-column label="状态" width="130"><template #default="{row}"><StatusBadge :value="row.status"/></template></el-table-column><el-table-column label="操作" width="300"><template #default="{row}"><el-button size="small" @click="open(row)">详情</el-button><el-button v-if="row.status==='ENABLED'" size="small" type="danger" plain @click="disable(row)">禁用</el-button><el-button v-else size="small" type="success" plain @click="enable(row)">启用</el-button><el-button v-if="row.roleCode==='USER'" size="small" type="primary" plain @click="promote(row)">晋升救助人员</el-button></template></el-table-column></el-table></div>
  <el-pagination class="pager" background layout="sizes,prev,pager,next,total" :page-sizes="[10,20,50]" :total="pager.total.value" v-model:page-size="pager.size.value" v-model:current-page="pager.page.value" @size-change="changePageSize" @current-change="load"/>
  <el-drawer v-model="drawer" title="用户详情" size="520px"><template v-if="detail"><el-descriptions :column="1" border><el-descriptions-item label="编号">{{detail.id}}</el-descriptions-item><el-descriptions-item label="账号">{{detail.account}}</el-descriptions-item><el-descriptions-item label="昵称">{{detail.nickname}}</el-descriptions-item><el-descriptions-item label="手机">{{detail.phone||'—'}}</el-descriptions-item><el-descriptions-item label="角色">{{displayText(detail.roleCode)}}</el-descriptions-item><el-descriptions-item label="状态">{{displayText(detail.status)}}</el-descriptions-item></el-descriptions><div v-if="detail.statistics" class="content-grid" style="grid-template-columns:repeat(2,1fr);margin-top:14px"><div v-for="(v,k) in detail.statistics" :key="k" class="card"><div class="muted">{{displayText(k)}}</div><div class="metric" style="font-size:26px">{{v}}</div></div></div></template></el-drawer>
</template>
<script setup>
import{ref,onMounted}from'vue';import{ElMessageBox}from'element-plus';import PageHeader from'../components/PageHeader.vue';import StatusBadge from'../components/StatusBadge.vue';import ListError from '../components/ListError.vue';import{adminApi}from'../api/index.js';import{usePagination}from'../composables/usePagination.js';import{displayText}from'../utils/displayText.js'
const pager=usePagination({pageSize:20}),keyword=ref(''),role=ref(''),drawer=ref(false),detail=ref(null)
async function load(){await pager.load(({page,size})=>adminApi.users({page,size,...(keyword.value.trim()?{keyword:keyword.value.trim()}:{}) ,...(role.value?{roleCode:role.value}:{})})).catch(()=>{})}function search(){pager.reset();load()}function changePageSize(){pager.reset();load()}
async function open(row){detail.value=await adminApi.user(row.id);drawer.value=true}async function disable(row){await ElMessageBox.confirm('确认禁用该账号？','禁用账号');await adminApi.disableUser(row.id);await load()}async function enable(row){await adminApi.enableUser(row.id);await load()}async function promote(row){await ElMessageBox.confirm('角色变化不改变历史业务数据所有权。确认晋升？','晋升救助人员');await adminApi.promoteRescuer(row.id);await load()}onMounted(load)
</script>
